<div class="card_unit<?php if ($force_open) { echo " open"; } ?>">
	<div class="imagecontainer togglebutton" onClick="<?php if (!$force_open) { echo "toggleCard(this.parentElement)"; } ?>">
		<img class="image" src="/asteria/image_detail/<?=$v($id)?>">
		<span class="element <?=$v($element)?>"></span>
		<span class="rarity r<?=$v($rarity)?>"></span>
		<?php if ($patch_change): ?>
			<span class="patch-change"><?=$v($patch_change)?></span>
		<?php endif ?>
	</div>
	
	<div class="name">
		<?=str_replace("&amp;nbsp;", "&nbsp;", $v($name))?>
		<div class="openInfo small">
			<?=$v($game)?>
			<div class="smallstats">
				<?php if (in_array($id, $collection_ids)): ?>
					<a class="icon remove smallbutton" onClick="toggleCollection(this, '<?=$v($id)?>')">Remove</a>
				<?php else: ?>
					<a class="icon add smallbutton" onClick="toggleCollection(this, '<?=$v($id)?>')">Add</a>
				<?php endif ?>
				<a class="icon copy smallbutton" onClick="copyInfo(this, '<?=$v($copyinfo)?>')">Copy</a>
				<a href="/asteria/unit/<?=$v($id)?>" class="icon link smallbutton">Link</a>
			</div>
		</div>
	</div>
	
	<div class="closeInfo">
		<div class="smallstats">
			<span class="icon hp text-hp"><?=$v($stats_hp)?></span>
			<span class="icon atk text-atk"><?=$v($stats_atk)?></span>
			<span class="icon def text-def"><?=$v($stats_def)?></span>
		</div>
		<div class="smallstats">
			<span><?php if ($ma_name) { echo $v($ma_summary_short); } else { echo "&nbsp;"; } ?></span>
			<span><?=$v($coop_type)?> Type</span>
		</div>
	</div>
	
	<div class="openInfo">
		<?php if ($awaken_info): ?>
			<div class="smallstats artemargins">
				<span class="icon star <?=$v($awaken_star_type)?>"><?=$v($awaken_info)?></span>
			</div>
			<a class="small" href="/asteria/<?=($awaken_related_id == $id) ? "partner" : "unit"?>/<?=$v($awaken_related_id)?>"><?=$v($awaken_link_label)?></a>
		<?php endif ?>
		
		<h5>Stats</h5>
		<div class="smallstats">
			<span class="icon hp text-hp"><?=$v($stats_hp)?></span>
			<span class="icon atk text-atk"><?=$v($stats_atk)?></span>
			<span class="icon def text-def"><?=$v($stats_def)?></span>
		</div>
		Co-op Type: 
			<span class="text-<?=$v($coop_type_short)?>"><?=$v($coop_type)?></span>
		
		<?php if ($ex_skill_tf): ?>
			<h5>Transformation</h5>
			<div class="small margins left"><?=$v($ex_skill_tf)?></div>
		<?php endif ?>
		
		<?php if ($ex_skill): ?>
			<h5>EX Skill</h5>
			<div class="small margins left"><?=$v($ex_skill)?></div>
		<?php endif ?>
		
		<?php if ($artes): ?>
			<h5>Artes</h5>
			<?php if ($tf_baseartes): ?>
				<?php foreach($tf_baseartes as $arte): ?>
					<?php $v->insert('card_unit_arte', $arte) ?>
				<?php endforeach ?>
				<h6><?=$v($tf_label)?></h6>
			<?php endif ?>
			<?php foreach($artes as $arte): ?>
				<?php $v->insert('card_unit_arte', $arte) ?>
			<?php endforeach ?>
		<?php endif ?>
		
		<?php if ($ma_name): ?>
			<h5>Mystic Arte</h5>
			<div class="small margins left">
				<span class="bold"><?=$v($ma_summary)?></span>: <?=$v($ma_description)?><br>
				<?php if ($ma_coopdiff): ?>
					<b>In Co-op Battle:</b> <?=$v($ma_coopdiff)?><br>
				<?php endif ?>
				<?php if ($ma_bond): ?>
					<b>Bond Potential:</b> <?=$v($ma_bond)?><br>
				<?php endif ?>
				<b>OL Charge:</b> <?=$v($ma_charge)?> (avg. <?=$v($ma_chargeturns["avg"])?> turn<?=$v($ma_chargeturns["avg_plural"])?>)
			</div>
			<?php if ($ma_ex_summary): ?>
				<h6>EX Mystic Arte</h6>
				<div class="small margins left">
					<span class="bold"><?=$v($ma_ex_summary)?></span>: <?=$v($ma_ex_description)?><br>
					<?php if ($ma_ex_coopdiff): ?>
						<b>In Co-op Battle:</b> <?=$v($ma_ex_coopdiff)?><br>
					<?php endif ?>
					<?php if ($ma_ex_bond): ?>
						<b>Bond Potential:</b> <?=$v($ma_ex_bond)?><br>
					<?php endif ?>
					<div>
						<b>OL Charge:</b> <?=$v($ma_charge + $ma_ex_charge)?> (<?=$v($ma_charge)?> + <?=$v($ma_ex_charge)?>, avg. <?=$v($ma_ex_chargeturns["avg"])?> turn<?=$v($ma_ex_chargeturns["avg_plural"])?>)
					</div>
				</div>
			<?php endif ?>
		<?php endif ?>
		
		<?php if ($ma_dual_name): ?>
			<div class="dualmaheader smallstats split left">
				<h5>Dual Mystic Arte</h5>
				<a href="/asteria/soul/<?=$v($ma_dual_soul_id)?>"><div class="inlinethumb soul"><img src="/asteria/assets/<?=$v($ma_dual_soul_image)?>"></div></a>
			</div>
			<div class="small margins left dualmargin">
				Required Soul: <a href="/asteria/soul/<?=$v($ma_dual_soul_id)?>"><?=$v($ma_dual_soul_name)?></a>
			</div>
			<div class="small margins left">
				<span class="bold"><?=$v($ma_dual_summary)?></span>: <?=$v($ma_dual_description)?><br>
				<?php if ($ma_dual_coopdiff): ?>
					<b>In Co-op Battle:</b> <?=$v($ma_dual_coopdiff)?><br>
				<?php endif ?>
				<?php if ($ma_dual_bond): ?>
					<b>Bond Potential:</b> <?=$v($ma_dual_bond)?><br>
				<?php endif ?>
				<b>OL Charge:</b> <?=$v($ma_dual_charge)?> (avg. <?=$v($ma_dual_chargeturns["avg"])?> turn<?=$v($ma_dual_chargeturns["avg_plural"])?>)
			</div>
			<?php if ($ma_dual_ex_summary): ?>
				<h6>Dual EX Mystic Arte</h6>
				<div class="small margins left">
					<span class="bold"><?=$v($ma_dual_ex_summary)?></span>: <?=$v($ma_dual_ex_description)?><br>
					<?php if ($ma_dual_ex_coopdiff): ?>
						<b>In Co-op Battle:</b> <?=$v($ma_dual_ex_coopdiff)?><br>
					<?php endif ?>
					<?php if ($ma_dual_ex_bond): ?>
						<b>Bond Potential:</b> <?=$v($ma_dual_ex_bond)?><br>
					<?php endif ?>
					<div>
						<b>OL Charge:</b> <?=$v($ma_dual_charge + $ma_dual_ex_charge)?> (<?=$v($ma_dual_charge)?> + <?=$v($ma_dual_ex_charge)?>, avg. <?=$v($ma_dual_ex_chargeturns["avg"])?> turn<?=$v($ma_dual_ex_chargeturns["avg_plural"])?>)
					</div>
				</div>
			<?php endif ?>
		<?php endif ?>
		
		<h5>Co-op Skill</h5>
		<div class="smallstats split margins">
			<span><?=$v($coop_name)?></span>
			<span class="element <?=$v($coop_element)?>"></span>
		</div>
		<div class="small margins left">
			<?=$v($coop_description)?>
		</div>
		
		<?php if ($souls): ?>
			<?php if (count($souls) > 1): ?>
				<h5>Soulmates</h5>
			<?php else: ?>
				<h5>Soulmate</h5>
			<?php endif ?>
			<?php foreach($souls as $soul): ?>
				<div class="smallstats split margins soulline">
					<span>
						<a href="/asteria/soul/<?=$v($soul["id"])?>"><div class="inlinethumb soul"><img src="/asteria/assets/<?=$v($soul["image"])?>"></div></a>
						<a href="/asteria/soul/<?=$v($soul["id"])?>"><?=str_replace("&amp;nbsp;", "&nbsp;", $v($soul["name"]))?></a>
					</span>
					<span class="small"><?=$v($soul["effect"])?></span>
				</div>
			<?php endforeach ?>
		<?php endif ?>
		
		<?php if (count($partner_info["partners"]) > 0): ?>
			<?php if (count($partner_info["partners"]) > 1): ?>
				<h5>Awakening Partners</h5>
			<?php else: ?>
				<h5>Awakening Partner</h5>
			<?php endif ?>
			<?php foreach($partner_info["partners"] as $partner): ?>
				<div class="smallstats split margins matchline">
					<span>
						<a href="/asteria/partner/<?=$v($partner["id"])?>"><div class="inlinethumb"><img src="/asteria/image_thumb/<?=$v($partner["id"])?>"></div></a>
						<a href="/asteria/partner/<?=$v($partner["id"])?>"><?=str_replace("&amp;nbsp;", "&nbsp;", $v($partner["name"]))?></a>
					</span>
					<span>
						<div class="element inline <?=$v($partner["element"])?>"></div>
					</span>
				</div>
			<?php endforeach ?>
		<?php endif ?>
		
		<?php if ($subquests): ?>
			<h6>Subquests Available</h6>
		<?php endif ?>
		
		<div style="height:1em"></div>
		<a href="/asteria/unit/<?=$v($id)?>" class="smallbutton">See All Information &#x25b6;</a>
		<div style="height:1em"></div>
	</div>
	<?php if (!$force_open): ?>
		<div class="name togglebutton" onClick="toggleCard(this.parentElement)">
			<span class="uparrow">&#x25B2;</span>
			<span class="downarrow">&#x25BC;</span>
		</div>
	<?php endif ?>
</div>