<?php $v->layout('layout', ['title' => 'Index']) ?>
<div class="container" style="padding-top: 4em">
	<b>Tales of Asteria has ended service on May 18th, 2023.</b><br>
	The Asteria Database will remain online for the foreseeable future.<br><br>
	<small>Thank you, Asteria team, for your work and the memories!</small><br><br>
	<a href="https://suyo.be/gallery/asteria_stamps/"><img src="/asteria/image/otsu.png"></a>
</div>
