<div class="row">
    <div class="four columns">
	    <b><?=$v($name)?></b><br>
	    <span class="small">Chance: <?=$v($chance)?>%</span>
        <?php if ($voice): ?>
            <br><div class="voice">
                <div class="closeInfo" onClick="toggleCard(this.parentElement)">
                    <img src="/asteria/image/icon_voice.svg" alt="Arte Use" title="Arte Use" class="closeInfo">
                    <span>Arte Use</span>
                </div>
                <audio class="openInfo" controls src="/asteria/assets/<?=$v($voice)?>" preload="none"></audio>
            </div>
        <?php endif ?>
    </div>
    <div class="eight columns">
	    <?=$v($description)?>
	    <?php if ($bond): ?>
	        <br>
	        <b class="title" title="Bond Potential">BP:</b> Increase attack power of all Light party units by 20% (current turn)
		<?php endif ?>
    </div>
</div>
