<?php $v->layout('layout', ['title' => 'Voices']) ?>
<style>
    .row {
        text-align: left;
    }

    .three.columns:nth-child(odd) {
        background-color: #eee;
    }
    
    .inlinethumb img {
        top: -1.5em;
    }
    
    .inlinethumb.soul {
        top: -1.5em;
    }
    
    .three.columns {
        display: flex;
        align-items: center;
        height: 4em;
        padding: 1em 0.5em;
    }
    
    .three.columns a {
        flex: 1 1 0;
        display: block;
        line-height: 1em;
    }
    
    @media (min-width: 550px) {
        .row:nth-child(even) {
            background-color: #ddd;
        }
        .row:nth-child(odd) {
            background-color: #eee;
        }
	    .three.columns {
	        background-color: unset !important;
        }
    }
</style>
<div class="container">
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/10010010"></div>
	        <a href="/asteria/voices/kur">Cress<br><small>クレス</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/10020010"></div>
	        <a href="/asteria/voices/min">Mint<br><small>ミント</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/10030010"></div>
	        <a href="/asteria/voices/che">Chester<br><small>チェスター</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/10040010"></div>
	        <a href="/asteria/voices/kla">Claus<br><small>クラース</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/10050010"></div>
	        <a href="/asteria/voices/arc">Arche<br><small>アーチェ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/10060010"></div>
	        <a href="/asteria/voices/suz">Suzu<br><small>すず</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/10070010"></div>
	        <a href="/asteria/voices/dha">Dhaos<br><small>ダオス</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/11010010"></div>
	        <a href="/asteria/voices/stn">Stahn<br><small>スタン</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/11020010"></div>
	        <a href="/asteria/voices/rte">Rutee<br><small>ルーティ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/11030010"></div>
	        <a href="/asteria/voices/lio">Leon<br><small>リオン</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/11040010"></div>
	        <a href="/asteria/voices/phi">Philia<br><small>フィリア</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/11050010"></div>
	        <a href="/asteria/voices/wdw">Woodrow<br><small>ウッドロウ</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/11060010"></div>
	        <a href="/asteria/voices/mry">Mary<br><small>マリー</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/11100010"></div>
	        <a href="/asteria/voices/lil">Lilith<br><small>リリス</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/11200010"></div>
	        <a href="/asteria/voices/mic">Miktran<br><small>ミクトラン</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/11260010"></div>
	        <a href="/asteria/voices/rtk">Rutee<br><small>ルーティ</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/12010010"></div>
	        <a href="/asteria/voices/rid">Reid<br><small>リッド</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/12020010"></div>
	        <a href="/asteria/voices/far">Farah<br><small>ファラ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/12030010"></div>
	        <a href="/asteria/voices/kee">Keele<br><small>キール</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/12040010"></div>
	        <a href="/asteria/voices/mer">Meredy<br><small>メルディ</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/12050010"></div>
	        <a href="/asteria/voices/fog">Fog<br><small>フォッグ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/12060010"></div>
	        <a href="/asteria/voices/cht">Chat<br><small>チャット</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/12110010"></div>
	        <a href="/asteria/voices/szl">Shizel<br><small>シゼル</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/13010010"></div>
	        <a href="/asteria/voices/kyl">Kyle<br><small>カイル</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/13020010"></div>
	        <a href="/asteria/voices/rea">Reala<br><small>リアラ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/13030010"></div>
	        <a href="/asteria/voices/lon">Loni<br><small>ロニ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/13040010"></div>
	        <a href="/asteria/voices/jds">Judas<br><small>ジューダス</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/13050010"></div>
	        <a href="/asteria/voices/nnl">Nanaly<br><small>ナナリー</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/13060010"></div>
	        <a href="/asteria/voices/hld">Harold<br><small>ハロルド</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/13070010"></div>
	        <a href="/asteria/voices/brb">Barbatos<br><small>バルバトス</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/13090020"></div>
	        <a href="/asteria/voices/frt">Fortuna<br><small>フォルトゥナ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/13100010"></div>
	        <a href="/asteria/voices/lim">Rimul<br><small>リムル</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/14010010"></div>
	        <a href="/asteria/voices/llo">Lloyd<br><small>ロイド</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/14020010"></div>
	        <a href="/asteria/voices/col">Colette<br><small>コレット</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/14030010"></div>
	        <a href="/asteria/voices/gen">Genis<br><small>ジーニアス</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/14040010"></div>
	        <a href="/asteria/voices/rfl">Raine<br><small>リフィル</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/14050010"></div>
	        <a href="/asteria/voices/kra">Kratos<br><small>クラトス</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/14060010"></div>
	        <a href="/asteria/voices/zer">Zelos<br><small>ゼロス</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/14070010"></div>
	        <a href="/asteria/voices/shi">Sheena<br><small>しいな</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/14080010"></div>
	        <a href="/asteria/voices/pre">Presea<br><small>プレセア</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/14110010"></div>
	        <a href="/asteria/voices/mts">Mithos<br><small>ミトス</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/14130010"></div>
	        <a href="/asteria/voices/ewn">Yuan<br><small>ユアン</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/14140020"></div>
	        <a href="/asteria/voices/ygg">Yggdrasil<br><small>ユグドラシル</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/15010010"></div>
	        <a href="/asteria/voices/vei">Veigue<br><small>ヴェイグ</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/15030010"></div>
	        <a href="/asteria/voices/mao">Mao<br><small>マオ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/15060010"></div>
	        <a href="/asteria/voices/tyt">Tytree<br><small>ティトレイ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/15070010"></div>
	        <a href="/asteria/voices/hil">Hilda<br><small>ヒルダ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/15210010"></div>
	        <a href="/asteria/voices/mlh">Milhaust<br><small>ミルハウスト</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/16010010"></div>
	        <a href="/asteria/voices/snl">Senel<br><small>セネル</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/16020010"></div>
	        <a href="/asteria/voices/shr">Shirley<br><small>シャーリィ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/16040010"></div>
	        <a href="/asteria/voices/chl">Chloe<br><small>クロエ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/16050010"></div>
	        <a href="/asteria/voices/nma">Norma<br><small>ノーマ</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/16070010"></div>
	        <a href="/asteria/voices/jay">Jay<br><small>ジェイ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/16080010"></div>
	        <a href="/asteria/voices/glu">Grune<br><small>グリューネ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/16320010"></div>
	        <a href="/asteria/voices/swz">Schwartz<br><small>シュヴァルツ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/16380010"></div>
	        <a href="/asteria/voices/kgl">Grune<br><small>グリューネ</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/17020010"></div>
	        <a href="/asteria/voices/tea">Tear<br><small>ティア</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/17030010"></div>
	        <a href="/asteria/voices/jad">Jade<br><small>ジェイド</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/17040010"></div>
	        <a href="/asteria/voices/ani">Anise<br><small>アニス</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/17050010"></div>
	        <a href="/asteria/voices/guy">Guy<br><small>ガイ</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/17060010"></div>
	        <a href="/asteria/voices/nat">Natalia<br><small>ナタリア</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/17090010"></div>
	        <a href="/asteria/voices/van">Van<br><small>ヴァン</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/17100010"></div>
	        <a href="/asteria/voices/asc">Asch<br><small>アッシュ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/17140010"></div>
	        <a href="/asteria/voices/art">Arietta<br><small>アリエッタ</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/17150010"></div>
	        <a href="/asteria/voices/syn">Sync<br><small>シンク</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/17230010"></div>
	        <a href="/asteria/voices/luk">Luke<br><small>ルーク</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/18010010"></div>
	        <a href="/asteria/voices/cai">Caius<br><small>カイウス</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/18020010"></div>
	        <a href="/asteria/voices/rub">Rubia<br><small>ルビア</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/19010020"></div>
	        <a href="/asteria/voices/psk">P. Kanonno<br><small>P・カノンノ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/20010010"></div>
	        <a href="/asteria/voices/ruc">Ruca<br><small>ルカ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/20020010"></div>
	        <a href="/asteria/voices/iri">Illia<br><small>イリア</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/20030010"></div>
	        <a href="/asteria/voices/spd">Spada<br><small>スパーダ</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/20040010"></div>
	        <a href="/asteria/voices/rcl">Ricardo<br><small>リカルド</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/20050010"></div>
	        <a href="/asteria/voices/anj">Ange<br><small>アンジュ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/20110010"></div>
	        <a href="/asteria/voices/kon">Kongwai<br><small>コンウェイ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/20140010"></div>
	        <a href="/asteria/voices/hst">Hasta<br><small>ハスタ</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/20150020"></div>
	        <a href="/asteria/voices/mat">Mathias<br><small>マティウス</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/21010010"></div>
	        <a href="/asteria/voices/emi">Emil<br><small>エミル</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/21020010"></div>
	        <a href="/asteria/voices/mrt">Marta<br><small>マルタ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/21030010"></div>
	        <a href="/asteria/voices/rtr">Richter<br><small>リヒター</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/21040010"></div>
	        <a href="/asteria/voices/ali">Alice<br><small>アリス</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/22010010"></div>
	        <a href="/asteria/voices/yur">Yuri<br><small>ユーリ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/22020010"></div>
	        <a href="/asteria/voices/est">Estelle<br><small>エステル</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/22030010"></div>
	        <a href="/asteria/voices/fla">Flynn<br><small>フレン</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/22040010"></div>
	        <a href="/asteria/voices/rap">Repede<br><small>ラピード</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/22050020"></div>
	        <a href="/asteria/voices/crl">Karol<br><small>カロル</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/22060010"></div>
	        <a href="/asteria/voices/rit">Rita<br><small>リタ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/22070010"></div>
	        <a href="/asteria/voices/rav">Raven<br><small>レイヴン</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/22080010"></div>
	        <a href="/asteria/voices/jdh">Judith<br><small>ジュディス</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/22090010"></div>
	        <a href="/asteria/voices/pti">Patty<br><small>パティ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/22100010"></div>
	        <a href="/asteria/voices/duk">Duke<br><small>デューク</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/22150010"></div>
	        <a href="/asteria/voices/swn">Schwann<br><small>シュヴァーン</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/23010010"></div>
	        <a href="/asteria/voices/shg">Shing<br><small>シング</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/23020010"></div>
	        <a href="/asteria/voices/koh">Kohaku<br><small>コハク</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/23030010"></div>
	        <a href="/asteria/voices/his">Hisui<br><small>ヒスイ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/23120010"></div>
	        <a href="/asteria/voices/crd">Creed<br><small>クリード</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/23180010"></div>
	        <a href="/asteria/voices/ais">Silver<br><small>シルバ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/24010010"></div>
	        <a href="/asteria/voices/eah">Kanonno E.<br><small>カノンノ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/24090020"></div>
	        <a href="/asteria/voices/bea">Kanonno E. [Ruin Bringer]<br><small>カノンノ・E</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/25010010"></div>
	        <a href="/asteria/voices/asb">Asbel<br><small>アスベル</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/25020010"></div>
	        <a href="/asteria/voices/sof">Sophie<br><small>ソフィ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/25030010"></div>
	        <a href="/asteria/voices/hub">Hubert<br><small>ヒューバート</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/25040010"></div>
	        <a href="/asteria/voices/chr">Cheria<br><small>シェリア</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/25050010"></div>
	        <a href="/asteria/voices/ric">Richard<br><small>リチャード</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/25060010"></div>
	        <a href="/asteria/voices/mlc">Malik<br><small>マリク</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/25070010"></div>
	        <a href="/asteria/voices/pas">Pascal<br><small>パスカル</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/25090010"></div>
	        <a href="/asteria/voices/eml">Emeraude<br><small>エメロード</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/25170010"></div>
	        <a href="/asteria/voices/rmd">Lambda<br><small>ラムダ</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/25500010"></div>
	        <a href="/asteria/voices/fas">Asbel [f Arc]<br><small>アスベル</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/26040010"></div>
	        <a href="/asteria/voices/lnd">Rody<br><small>ロディ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/27010030"></div>
	        <a href="/asteria/voices/grs">Kanonno G.<br><small>カノンノ・G</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/27020020"></div>
	        <a href="/asteria/voices/raz">Lazaris<br><small>ラザリス</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/28010020"></div>
	        <a href="/asteria/voices/jud">Jude<br><small>ジュード</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/28020010"></div>
	        <a href="/asteria/voices/mil">Milla<br><small>ミラ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/28030030"></div>
	        <a href="/asteria/voices/alv">Alvin<br><small>アルヴィン</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/28040030"></div>
	        <a href="/asteria/voices/lei">Leia<br><small>レイア</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/28050030"></div>
	        <a href="/asteria/voices/eli">Elize<br><small>エリーゼ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/28060020"></div>
	        <a href="/asteria/voices/ren">Rowen<br><small>ローエン</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb soul"><img src="/asteria/assets/image/soul/detail/detail_soul_tip_2807002.png"></div>
	        <a href="/asteria/voices/tip">Teepo<br><small>ティポ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/28080020"></div>
	        <a href="/asteria/voices/gai">Gaius<br><small>ガイアス</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/28110010"></div>
	        <a href="/asteria/voices/wgl">Wingul<br><small>ウィンガル</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/28170030"></div>
	        <a href="/asteria/voices/mus">Muzét<br><small>ミュゼ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/31010010"></div>
	        <a href="/asteria/voices/lud">Ludger<br><small>ルドガー</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/31020010"></div>
	        <a href="/asteria/voices/ell">Elle<br><small>エル</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/31030010"></div>
	        <a href="/asteria/voices/jul">Julius<br><small>ユリウス</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/31060030"></div>
	        <a href="/asteria/voices/bzl">Bisley<br><small>ビズリー</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/31070010"></div>
	        <a href="/asteria/voices/vic">Victor<br><small>ヴィクトル</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/31130010"></div>
	        <a href="/asteria/voices/mll">Milla [Fractured]<br><small>ミラ</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/31140010"></div>
	        <a href="/asteria/voices/ifj">Jude<br><small>ジュード</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/31160010"></div>
	        <a href="/asteria/voices/ifi">Leia<br><small>レイア</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/31170010"></div>
	        <a href="/asteria/voices/ife">Elize<br><small>エリーゼ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/31190010"></div>
	        <a href="/asteria/voices/ifu">Muzét<br><small>ミュゼ</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/31200010"></div>
	        <a href="/asteria/voices/ifg">Gaius<br><small>ガイアス</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/33010010"></div>
	        <a href="/asteria/voices/sor">Sorey<br><small>スレイ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/33020010"></div>
	        <a href="/asteria/voices/als">Alisha<br><small>アリーシャ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/33030010"></div>
	        <a href="/asteria/voices/mik">Mikleo<br><small>ミクリオ</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/33040010"></div>
	        <a href="/asteria/voices/edn">Edna<br><small>エドナ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/33060010"></div>
	        <a href="/asteria/voices/dez">Dezel<br><small>デゼル</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/33070010"></div>
	        <a href="/asteria/voices/zav">Zaveid<br><small>ザビーダ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/33080010"></div>
	        <a href="/asteria/voices/ros">Rose<br><small>ロゼ</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/33140020"></div>
	        <a href="/asteria/voices/sim">Symonne<br><small>サイモン</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/33170020"></div>
	        <a href="/asteria/voices/hel">Heldalf<br><small>ヘルダルフ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/33210010"></div>
	        <a href="/asteria/voices/las">Lailah<br><small>ライラ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/34010010"></div>
	        <a href="/asteria/voices/vec">Velvet<br><small>ベルベット</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/34020010"></div>
	        <a href="/asteria/voices/lap">Laphicet<br><small>ライフィセット</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/34030010"></div>
	        <a href="/asteria/voices/rok">Rokurou<br><small>ロクロウ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/34040010"></div>
	        <a href="/asteria/voices/mag">Magilou<br><small>マギルゥ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/34050010"></div>
	        <a href="/asteria/voices/eiz">Eizen<br><small>アイゼン</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/34060010"></div>
	        <a href="/asteria/voices/ele">Eleanor<br><small>エレノア</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/34080010"></div>
	        <a href="/asteria/voices/sil">Seres<br><small>シアリーズ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/34100010"></div>
	        <a href="/asteria/voices/bza">Zaveid<br><small>ザビーダ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/34110020"></div>
	        <a href="/asteria/voices/ter">Teresa<br><small>テレサ</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/34120010"></div>
	        <a href="/asteria/voices/cte">Teresa [Therionized]<br><small>テレサ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/34130010"></div>
	        <a href="/asteria/voices/osc">Oscar<br><small>オスカー</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/34150010"></div>
	        <a href="/asteria/voices/sig">Shigure<br><small>シグレ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/34160010"></div>
	        <a href="/asteria/voices/mec">Melchior<br><small>メルキオル</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/34190010"></div>
	        <a href="/asteria/voices/kan">Innominat<br><small>カノヌシ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/34200010"></div>
	        <a href="/asteria/voices/atc">Artorius<br><small>アルトリウス</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/37020010"></div>
	        <a href="/asteria/voices/alp">Alphen<br><small>アルフェン</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/37030010"></div>
	        <a href="/asteria/voices/son">Shionne<br><small>シオン</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/37040010"></div>
	        <a href="/asteria/voices/rin">Rinwell<br><small>リンウェル</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/37060010"></div>
	        <a href="/asteria/voices/law">Law<br><small>ロウ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/37070010"></div>
	        <a href="/asteria/voices/kis">Kisara<br><small>キサラ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/37080010"></div>
	        <a href="/asteria/voices/doh">Dohalim<br><small>テュオハリム</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/37090020"></div>
	        <a href="/asteria/voices/vho">Vholran<br><small>ヴォルラーン</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/38010010"></div>
	        <a href="/asteria/voices/lal">Allen<br><small>アレン</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/38020010"></div>
	        <a href="/asteria/voices/lsa">Sara<br><small>サラ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/38030010"></div>
	        <a href="/asteria/voices/lze">Zephyr<br><small>ゼファー</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/38040010"></div>
	        <a href="/asteria/voices/lka">Kana<br><small>カナ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/38050010"></div>
	        <a href="/asteria/voices/lri">Lippy<br><small>リッピ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/39010010"></div>
	        <a href="/asteria/voices/ckh">Kanata<br><small>カナタ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/39020010"></div>
	        <a href="/asteria/voices/cmi">Misella<br><small>ミゼラ</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/39030010"></div>
	        <a href="/asteria/voices/cvi">Vicious<br><small>ヴィシャス</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/39040010"></div>
	        <a href="/asteria/voices/caa">Aegis<br><small>イージス</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/39050010"></div>
	        <a href="/asteria/voices/cya">Yuna<br><small>ユナ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/90000020"></div>
	        <a href="/asteria/voices/ole">Orie<br><small>オリエ</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/90020030"></div>
	        <a href="/asteria/voices/all">Lloyd [Fang]<br><small>ファング</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/90030020"></div>
	        <a href="/asteria/voices/ayu">Yuri [Claw]<br><small>クロー</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/90040030"></div>
	        <a href="/asteria/voices/ami">Milla [Roar]<br><small>ロアー</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/90080010"></div>
	        <a href="/asteria/voices/wtl">Tirug [Purified]<br><small>ティルグ</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/90090030"></div>
	        <a href="/asteria/voices/aas">Asbel [Dark Puppet]<br><small>アスベル</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/90100030"></div>
	        <a href="/asteria/voices/aed">Edna [Dark Puppet]<br><small>エドナ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/90110020"></div>
	        <a href="/asteria/voices/imi">Mikleo [Fractured Dimension]<br><small>ミクリオ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/90120010"></div>
	        <a href="/asteria/voices/ime">Meredy [Fractured Dimension]<br><small>メルディ</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/90130010"></div>
	        <a href="/asteria/voices/ias">Asch [Fractured Dimension]<br><small>アッシュ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/90140030"></div>
	        <a href="/asteria/voices/iso">Sorey [Lord of Calamity]<br><small>スレイ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/90150020"></div>
	        <a href="/asteria/voices/ike">Keele [Mad Scientist Seeking Glory]<br><small>キール</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/90160030"></div>
	        <a href="/asteria/voices/ilu">Luke [Carrying The Burden]<br><small>ルーク</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/90180020"></div>
	        <a href="/asteria/voices/ier">Elle ["Fate of the Twin Stars" Arc]<br><small>エル</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/95010010"></div>
	        <a href="/asteria/voices/ska">Kasane<br><small>カサネ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/95020010"></div>
	        <a href="/asteria/voices/iko">Kohaku<br><small>心白</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/95030010"></div>
	        <a href="/asteria/voices/iay">Aya<br><small>亜夜</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/95040010"></div>
	        <a href="/asteria/voices/rna">Nazar<br><small>ナーザ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/95050010"></div>
	        <a href="/asteria/voices/rba">Bardo<br><small>バルド</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/95060010"></div>
	        <a href="/asteria/voices/rmr">Mercuria<br><small>メルクリア</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99110010"></div>
	        <a href="/asteria/voices/gbp">Percival<br><small>パーシヴァル</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99120010"></div>
	        <a href="/asteria/voices/gbk">Cagliostro<br><small>カリオストロ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99130010"></div>
	        <a href="/asteria/voices/gbf">Ferry<br><small>フェリ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99200010"></div>
	        <a href="/asteria/voices/kit">Kitty White<br><small>キティ ホワイト</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99500010"></div>
	        <a href="/asteria/voices/iah">Haruka<br><small>春香</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99510010"></div>
	        <a href="/asteria/voices/ihm">Miki<br><small>美希</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99520010"></div>
	        <a href="/asteria/voices/isu">Uzuki<br><small>卯月</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99530010"></div>
	        <a href="/asteria/voices/ijm">Mika<br><small>美嘉</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99540010"></div>
	        <a href="/asteria/voices/iat">Touma<br><small>冬馬</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99550010"></div>
	        <a href="/asteria/voices/iis">Shiki<br><small>四季</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99560010"></div>
	        <a href="/asteria/voices/ikm">Mirai<br><small>未来</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99570010"></div>
	        <a href="/asteria/voices/ihs">Serika<br><small>星梨花</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99580010"></div>
	        <a href="/asteria/voices/ikc">Chihaya<br><small>千早</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99590010"></div>
	        <a href="/asteria/voices/iks">Shika<br><small>詩花</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99600010"></div>
	        <a href="/asteria/voices/jik">Siegfried<br><small>ジークフリート</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99610010"></div>
	        <a href="/asteria/voices/nar">Narmaya<br><small>ナルメア</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99800010"></div>
	        <a href="/asteria/voices/krm">Curry Meshi<br><small>カレーメシくん</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99820010"></div>
	        <a href="/asteria/voices/itt">Teru<br><small>輝</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99830010"></div>
	        <a href="/asteria/voices/iak">Hideo<br><small>英雄</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99840010"></div>
	        <a href="/asteria/voices/dam">Damuron<br><small>ダミュロン</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99890010"></div>
	        <a href="/asteria/voices/cla">Claudia<br><small>クローディア</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99900010"></div>
	        <a href="/asteria/voices/rik">Ix<br><small>イクス</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99910010"></div>
	        <a href="/asteria/voices/rmi">Mileena<br><small>ミリーナ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99920010"></div>
	        <a href="/asteria/voices/rko">Kocis<br><small>コーキス</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99930010"></div>
	        <a href="/asteria/voices/rka">Karia<br><small>カーリャ</small></a>
	    </div>
	</div>
	<div class="row">
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99940010"></div>
	        <a href="/asteria/voices/rph">Phantom<br><small>ファントム</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99950020"></div>
	        <a href="/asteria/voices/rpl">Phillip<br><small>フィリップ</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99970010"></div>
	        <a href="/asteria/voices/rma">Marcus<br><small>マーク</small></a>
	    </div>
	    <div class="three columns">
	        <div class="inlinethumb"><img src="/asteria/image_thumb/99980010"></div>
	        <a href="/asteria/voices/syu">Yuito<br><small>ユイト</small></a>
	    </div>
	</div>
</div>
